
resources:
- name: config
  type: git
  source:
    uri: https://github.com/t3hprofit/concoursefun
    branch: master
    paths:
    - ./**

jobs:
  - name: GetFileName
    plan:
      - get: config
      - task: GetFileName
        file: config/testvar.yml
        input_mapping:
          product: config
