resource_types:
- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:

- name: product
  type: file-url
  source: https://github.com/t3hprofit/oneops.github.io/blob/master/README.md
  filename: README.md

jobs:
  - name: GetFileName
  plan:
    - aggregate:
      - get: product
      