resource_types:
- name: static
  type: docker-image
  source: { repository: ktchen14/static-resource }

resources:
- name: config
  type: git
  source:
    uri: https://github.com/t3hprofit/concoursefun
    branch: master
    paths:
    - ./**

- name: my-secret
  type: static
  source:
    producturl: "www.google.com"
    username: t3hprofit


jobs:
  - name: GetFileName
    plan:
      - get: config
      - get: my-secret
      - task: GetFileName
        file: config/testvar.yml
        input_mapping:
          product: my-secret
